PMM-9863 remove yum-cron
percona/pmm-managed pull request #1086
Opened 2022-04-23 00:56 UTC by atymchuk

PMM-9863

Build: [SUBMODULES-2459](https://github.com/Percona-Lab/pmm-submodules/pull/2459)

2022-04-23 09:26 UTC, BupycHuk approved these changes

2022-04-23 09:26 UTC, BupycHuk requested changes
Tests are failing, cron.log still exists in container

2022-04-23 10:49 UTC, atymchuk commented
> Tests are failing, cron.log still exists in container

It's expected, this is why I left a comment up above :)

2022-04-23 11:57 UTC, BupycHuk approved these changes
Sorry, missed that comment

2022-04-24 11:23 UTC, artemgavrilov approved these changes

2022-04-24 13:36 UTC, nikita-b approved these changes

2022-04-24 13:48 UTC, merged