PMM-6038 Proto.
percona/pmm-managed pull request #439
Opened 2020-08-18 08:02 UTC by JiriCtvrtka

2020-08-24 08:28 UTC, BupycHuk commented on services/management/grpc/actions_server.go
> +	agent, err := models.FindAgentByID(s.db.Querier, req.PmmAgentId)
No, we should check for type.

2020-08-24 08:34 UTC, BupycHuk requested changes

2020-08-24 08:34 UTC, BupycHuk commented on services/management/grpc/actions_server.go
> +	if agent.AgentID != req.PmmAgentId {
this always will be true

2020-08-24 11:12 UTC, BupycHuk approved these changes
LGTM, just one comment.
Please request review from @percona-csalguero for all PRs.

2020-08-24 11:12 UTC, BupycHuk commented on services/management/grpc/actions_server.go
> +		return nil, fmt.Errorf("pmm-agent has type %s not %s", agent.AgentType, models.PMMAgentType)
Couldn't find pmm-agent to run action

2020-08-25 05:03 UTC, BupycHuk requested changes

2020-08-25 05:03 UTC, BupycHuk commented on services/management/grpc/actions_server.go
> +	agent, err := models.FindAgentByID(s.db.Querier, req.PmmAgentId)
find pmm-agents by field RunsOnNodeID which should be equal to req.NodeID. For it use `models.FindPMMAgentsRunningOnNode`.
Then check that passed pmm-agent id in the list by using `models.FindPmmAgentIDToRunAction`.

2020-08-25 05:03 UTC, BupycHuk commented on services/management/grpc/actions_server.go
> +	if agent.AgentType != models.NodeExporterType {
This check can be removed.

2020-08-25 05:03 UTC, BupycHuk commented on services/management/grpc/actions_server.go
> +	if pointer.GetString(agent.NodeID) != req.NodeId {
This check can be removed.

2020-08-25 05:03 UTC, BupycHuk commented on services/management/grpc/actions_server.go
> +func (s *actionsServer) StartPTSummaryAction(ctx context.Context, req *managementpb.StartPTSummaryActionRequest) (*managementpb.StartPTSummaryActionResponse, error) {
Place this method above CancelAction

2020-08-25 06:18 UTC, BupycHuk approved these changes

2020-08-25 06:18 UTC, BupycHuk commented on Gopkg.toml
> +  branch = "PMM-6038-pt-summary"
TODO:

2020-08-26 09:44 UTC, JiriCtvrtka commented
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1065

2020-08-28 12:14 UTC, merged