PMM-6130 pmm managed api k8 clusters
percona/pmm-managed pull request #440
Opened 2020-08-18 18:07 UTC by BupycHuk

2020-08-25 08:44 UTC, AlekSi commented on models/agent_helpers.go
> +		return nil, errors.Wrap(err, "failed to delete Agent")
WHOA

2020-08-25 08:44 UTC, AlekSi commented on models/kubernetes_helpers.go
> +		return status.Errorf(codes.AlreadyExists, "Cluster with ID %q already exists.", id)
"Kubernetes Cluster", not just "Cluster"

2020-08-25 08:44 UTC, AlekSi commented on models/kubernetes_helpers.go
> +		return status.Errorf(codes.AlreadyExists, "Cluster with Name %q already exists.", name)
"Kubernetes Cluster", not just "Cluster"

2020-08-25 08:44 UTC, AlekSi commented on models/kubernetes_helpers.go
> +// FindAllKubernetesClusters returns all kubernetes clusters.
Kubernetes, with capital K

2020-08-25 08:44 UTC, AlekSi commented on models/kubernetes_helpers.go
> +// FindKubernetesClusterByName finds a kubernetes cluster with provided name.
Kubernetes, with capital K

2020-08-25 08:44 UTC, AlekSi commented on models/kubernetes_helpers.go
> +		return nil, status.Errorf(codes.NotFound, "Cluster with name %q not found.", name)
"Kubernetes Cluster", not just "Cluster"

Please check all other places

2020-08-25 08:44 UTC, AlekSi commented on models/kubernetes_helpers.go
> +// CreateKubernetesClusterParams contains all params required to create kubernetes cluster.
Kubernetes, with capital K

Please check all other places

2020-08-25 08:44 UTC, AlekSi commented on models/kubernetes_helpers.go
> +func CreateKubernetesCluster(q *reform.Querier, params CreateKubernetesClusterParams) (*KubernetesCluster, error) {
Accept pointer for consistency?

2020-08-25 08:44 UTC, AlekSi commented on models/kubernetes_helpers_test.go
> +	sqlDB := testdb.Open(t, models.SetupFixtures, nil)
I think `testdb.Open` already uses t.Cleanup. We can avoid adding `require.NoError(t, sqlDB.Close())` below in a new code

2020-08-25 08:44 UTC, AlekSi commented on models/kubernetes_models.go
> +	_ reform.BeforeInserter = (*ActionResult)(nil)
⚠️ Not ActionResult

2020-08-25 08:44 UTC, AlekSi commented on services/management/dbaas/kubernetes_server_test.go
> +			require.NoError(t, sqlDB.Close())
Already done in t.Cleanup

2020-08-25 09:36 UTC, AlekSi approved these changes

2020-08-25 09:37 UTC, AlekSi requested changes
CI fails.

U DO NOT RUN TESTS LOCALLY? 😆

2020-08-25 09:50 UTC, BupycHuk commented
I do, but I have some failing tests locally because of network connection and I lost these two among them.

2020-08-25 11:34 UTC, JiriCtvrtka approved these changes

2020-08-26 12:26 UTC, AlekSi approved these changes

2020-09-01 13:14 UTC, merged