PMM-6567 pg_stat_monitor
percona/pmm-managed pull request #457
Opened 2020-09-10 07:15 UTC by JiriCtvrtka

[PMM-XXXX](https://jira.percona.com/browse/PMM-XXXX)

- [ ] Build: https://github.com/Percona-Lab/pmm-submodules/pull/0

- [ ] Links to other linked pull requests (optional).
---
- [ ] Tests passed.
- [ ] Feature build pass.
- [ ] (Re)requested review.
- [ ] Fix conflicts with target branch.
- [ ] Update API dependency.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

2020-09-16 09:09 UTC, BupycHuk requested changes
Everything is looks ok except two things.
1. You forgot about disable_query_examples
2. Inventory API was out of scope of this task, but let's keep it :)

2020-09-16 12:54 UTC, BupycHuk requested changes

2020-09-16 12:54 UTC, BupycHuk commented on services/converters.go
> +		return &inventorypb.QANPostgreSQLPgStatMonitorAgent{
`disable_query_examples` missed

2020-09-16 13:37 UTC, JiriCtvrtka commented on services/converters.go
> +		return &inventorypb.QANPostgreSQLPgStatMonitorAgent{
Right, thanks.

2020-09-17 08:29 UTC, AlekSi commented
There is a conflict now

2020-09-18 08:55 UTC, JiriCtvrtka commented
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1104

PRs:
PMM - https://github.com/percona/pmm/pull/584
PMM managed - https://github.com/percona/pmm-managed/pull/457
PMM API tests - https://github.com/Percona-Lab/pmm-api-tests/pull/124
PMM agent - https://github.com/percona/pmm-agent/pull/186

2020-09-18 09:15 UTC, BupycHuk approved these changes

2020-09-18 11:17 UTC, askomorokhov approved these changes
Looks good to me.

2020-09-18 11:17 UTC, askomorokhov commented on Gopkg.toml
> +  branch = "PMM-6567-pg-monitor"
Please change the branch back before marge.

2020-09-22 14:06 UTC, AlekSi commented
@JiriCtvrtka please resolve merge conflicts

2020-09-24 11:30 UTC, merged