PMM-6401 drop prometheus
percona/pmm-managed pull request #486
Opened 2020-10-13 16:58 UTC by valyala

[PMM-6401](https://jira.percona.com/browse/PMM-6401)

- [x] Build: https://github.com/Percona-Lab/pmm-submodules/pull/1157

- [x] Links to other linked pull requests:
  * https://github.com/percona/pmm-managed/pull/485
  * https://github.com/percona/pmm-server-packaging/pull/171
---
- [x] Tests passed.
- [x] Feature build pass.
- [ ] (Re)requested review.
- [ ] Fix conflicts with target branch.
- [ ] Update API dependency.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

2020-10-20 09:09 UTC, BupycHuk approved these changes

2020-10-30 08:46 UTC, AlekSi requested changes
Tests fails

2020-10-30 09:33 UTC, f41gh7 commented
> Tests fails

yes, its expected, because i've changed docker image to the base dev image, instead of FB.

2020-11-04 16:10 UTC, AlekSi approved these changes

2020-11-04 16:19 UTC, merged