Replace dep with go mod
percona/pmm-managed pull request #524
Opened 2020-11-18 14:35 UTC by Dasio

Hi,
I tried to migrate dependency manager from deprecated dep to new go mod.

Is there any reason which maybe I could oversee, why you want to keep dep?

---
- [x] Tests passed.
- [ ] Feature build pass.
- [ ] (Re)requested review.
- [ ] Fix conflicts with target branch.
- [ ] Update API dependency.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

2020-11-18 14:59 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/pmm-managed?pullRequest=524) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm-managed?pullRequest=524) before we can accept your contribution.<br/><hr/>**Dasio** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm-managed?pullRequest=524) it.</sub>

2020-12-06 08:19 UTC, AlekSi requested changes
Hi. Thank you for your contribution. There is no reason why we keep dep other than a lack of time. However, the migration is not that straightforward for v2 projects. May you update that PR to keep vendor/ directory and fix CI?

2020-12-06 08:19 UTC, AlekSi commented on Makefile.devcontainer
> -	go-sumtype ./vendor/... ./...
We want to keep go-sumtype tool and vendor/ directory

2020-12-14 12:54 UTC, Dasio commented
Closing this PR. If I had time, I would create new proper PR, there is really outdated vendor deps which upgrade wasn't so straightforward.

2020-12-14 12:54 UTC, closed without merging