PMM-6969 IA rules API
percona/pmm-managed pull request #554
Opened 2020-12-02 11:47 UTC by artemgavrilov

[PMM-XXXX](https://jira.percona.com/browse/PMM-XXXX)

- [ ] Build: https://github.com/Percona-Lab/pmm-submodules/pull/0

- [ ] Links to other linked pull requests (optional).
---
- [ ] Tests passed.
- [ ] Feature build pass.
- [ ] (Re)requested review.
- [ ] Fix conflicts with target branch.
- [ ] Update API dependency.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

2020-12-08 16:51 UTC, AlekSi commented
There are conflicts now

2020-12-09 23:57 UTC, AlekSi requested changes
Merge conflicts

2020-12-10 08:35 UTC, palash25 reviewed
few small comments, just skimmed through, will review it once again in some time

2020-12-10 18:55 UTC, palash25 approved these changes

2020-12-15 12:50 UTC, artemgavrilov commented
*resolving conflicts

2020-12-15 13:05 UTC, AlekSi commented on Gopkg.toml
> +  branch = "release/2.13"
PMM-2.0 now

2020-12-15 13:05 UTC, AlekSi commented on Gopkg.toml
> +  branch = "pmm-2.13"
main now

2020-12-16 15:39 UTC, AlekSi approved these changes

2020-12-16 15:58 UTC, merged