PMM-5980 Add suspend/resume pxc.
percona/pmm-managed pull request #560
Opened 2020-12-04 20:58 UTC by askomorokhov

[https://jira.percona.com/browse/PMM-5980](https://jira.percona.com/browse/PMM-5980)

- [ ] Build: https://github.com/Percona-Lab/pmm-submodules/pull/0

- [ ] Links to other linked pull requests (optional).
---
- [ ] Tests passed.
- [ ] Feature build pass.
- [ ] (Re)requested review.
- [ ] Fix conflicts with target branch.
- [ ] Update API dependency.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

2020-12-10 12:13 UTC, percona-csalguero approved these changes

2020-12-11 07:55 UTC, JiriCtvrtka approved these changes

2020-12-11 13:00 UTC, BupycHuk requested changes
The same comments as for https://github.com/percona/pmm-managed/pull/559

2020-12-11 13:36 UTC, askomorokhov commented on services/management/dbaas/xtradb_cluster_service.go
> +	if settings.PMMPublicAddress != "" {
yes, was left from dev code.

2020-12-11 13:44 UTC, BupycHuk approved these changes

2020-12-16 14:45 UTC, merged