PMM-6909 Add createdAt field to templates
percona/pmm-managed pull request #565
Opened 2020-12-07 17:46 UTC by artemgavrilov

[PMM-XXXX](https://jira.percona.com/browse/PMM-XXXX)

- [ ] Build: https://github.com/Percona-Lab/pmm-submodules/pull/0

- [ ] Links to other linked pull requests (optional).
---
- [ ] Tests passed.
- [ ] Feature build pass.
- [ ] (Re)requested review.
- [ ] Fix conflicts with target branch.
- [ ] Update API dependency.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

2020-12-08 10:27 UTC, artemgavrilov commented on services/management/ia/templates_service.go
> +	ruleFileDir = "/tmp/ia3/"
Just to fix tests

2020-12-08 12:43 UTC, palash25 approved these changes

2020-12-08 12:47 UTC, BupycHuk approved these changes

2020-12-09 23:56 UTC, AlekSi requested changes
There are conflicts now

2020-12-10 10:46 UTC, AlekSi approved these changes

2020-12-10 10:47 UTC, merged