PMM-7595 Use uint64 for disk and other values to avoid overflow
percona/pmm-managed pull request #696
Opened 2021-03-15 08:17 UTC by jprukner

[PMM-7595](https://jira.percona.com/browse/PMM-7595)

- [ ] Build: https://github.com/Percona-Lab/pmm-submodules/pull/0

- [ ] Links to other linked pull requests (optional).
---
- [ ] Tests passed.
- [ ] Feature build pass.
- [ ] (Re)requested review.
- [ ] Fix conflicts with target branch.
- [ ] Update API dependency.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

2021-03-16 19:07 UTC, BupycHuk approved these changes

2021-03-16 19:07 UTC, BupycHuk requested changes
Please fix tests

2021-03-17 09:32 UTC, jprukner commented
> Please fix tests

@BupycHuk I don't know how to fix SaaS tests. Fixed the ones related to my code changes.

2021-03-17 10:24 UTC, BupycHuk approved these changes

2021-03-19 12:48 UTC, Dasio approved these changes

2021-03-29 12:01 UTC, merged