PMM-7888 TLS for PostgreSQL
percona/pmm-managed pull request #781
Opened 2021-06-09 18:44 UTC by percona-csalguero

[PMM-7888 enabling percona to connect to Postgres using client certificates](https://jira.percona.com/browse/PMM-7888)

- [ ] Build: https://github.com/Percona-Lab/pmm-submodules/pull/0

- [Feature build](https://github.com/Percona-Lab/pmm-submodules/pull/1842)
- [pmm](https://github.com/percona/pmm/pull/749)
---
- [x] Tests passed.
- [ ] Feature build pass.
- [x] Update API dependency.

2021-06-09 23:14 UTC, BupycHuk requested changes

2021-06-09 23:14 UTC, BupycHuk commented on models/agent_model.go
> +	TLSKey  string `json:"tls_key"`
let's use ssl_ prefix since PostgreSQL uses that naming.

2021-06-09 23:14 UTC, BupycHuk commented on models/agent_model.go
> +							q.Set(key, tdp.Left+" .TextFiles.tlsKey "+tdp.Right)
as far as I see `s.Files()` returns
```
map[string]string{
				"ssl_ca_file":   s.PostgreSQLOptions.TLSCa,
				"ssl_cert_file": s.PostgreSQLOptions.TLSCert,
				"ssl_key_file":  s.PostgreSQLOptions.TLSKey,
			}
```
so this code will be skipped.
Please add more tests.

2021-06-11 10:46 UTC, JiriCtvrtka requested changes
Here should be also pmm-agent PR for actions (like explain).

2021-06-21 13:26 UTC, askomorokhov commented on models/agent_model.go
> +						//q.Set("ssl_ca_file", tdp.Left+".TextFiles.tlsCa"+tdp.Right)
Please removed commented line.

2021-06-21 13:28 UTC, askomorokhov approved these changes

2021-06-22 07:40 UTC, JiriCtvrtka approved these changes

2021-07-04 20:51 UTC, BupycHuk approved these changes

2021-07-14 07:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/percona/pmm-managed?pullRequest=781) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/percona/pmm-managed?pullRequest=781) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: percona-csalguero<br/>:x: askomorokhov<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/percona/pmm-managed?pullRequest=781) it.</sub>

2021-07-27 07:07 UTC, merged