PMM-9068: Test SMTP config
percona/pmm-managed pull request #870
Opened 2021-11-22 09:58 UTC by oter

[PMM-9068](https://jira.percona.com/browse/PMM-9068)

- [ ] Build: https://github.com/Percona-Lab/pmm-submodules/pull/0

- [ ] Links to other linked pull requests (optional).
---
- [ ] Tests passed.
- [ ] Feature build pass.
- [ ] (Re)requested review.
- [ ] Fix conflicts with target branch.
- [ ] Update API dependency.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

2021-11-24 17:06 UTC, artemgavrilov requested changes

2021-11-24 17:06 UTC, artemgavrilov commented on services/server/server.go
> +	}
IMHO that looks much more simple:
```suggestion
	if err != nil {
		if errors.As(err, &errInvalidArgument) {
			return nil, status.Errorf(codes.InvalidArgument, "Cannot send email: %s.", errInvalidArgument.Details)
		}

		return nil, status.Errorf(codes.Internal, "Cannot send email: %s.", err.Error())
	}
```

2021-11-25 14:54 UTC, oter commented on services/server/server.go
> +		return nil, status.Error(codes.InvalidArgument, fmt.Sprintf("Invalid argument: %s.", err.Error()))
done

2021-11-25 14:56 UTC, oter commented on services/server/server.go
> +	}
done

2021-11-25 16:20 UTC, oter commented on services/alertmanager/emailer.go
> +	alertmanagerEmail := email.New(emailConfig, tmpl, kitlog.NewNopLogger())
done

2021-11-26 10:56 UTC, artemgavrilov approved these changes

2021-11-29 08:02 UTC, yurkovychv approved these changes

2021-12-15 14:13 UTC, merged